<?php

declare(strict_types = 1);

namespace Pyz\Shared\OpenAi;

interface OpenAiConstants
{
    public const OPENAI_API_KEY = 'OPENAI_API_KEY';
    public const OPENAI_API_DEBUG_ERROR_RENDERER_PROMPT_NAME = 'OPENAI_ERROR_HANDLER_PROMPT_CLI';
    public const OPENAI_API_DEBUG_ERROR_RENDERER_PROMPT_NAME_FIXER = 'OPENAI_API_DEBUG_ERROR_RENDERER_PROMPT_NAME_FIXER';
    public const OPENAI_API_DEBUG_ERROR_RENDERER_PROMPT_NAME_5_YEARS = 'OPENAI_API_DEBUG_ERROR_RENDERER_PROMPT_NAME_5_YEARS';
}
